package autoGeneratedCodeFromAstah;

public abstract class Employee {

	private String name;

	private Date personNumber;

	private Enum category;

	private double salary;

	private static int employeeID;

	private double bonus;

	public void calculateSalary() {

	}

	public void calculateBonus() {

	}

}
