package autoGeneratedCodeFromAstah;

public class Update {

	public class EmployeeManagement {

		private ArrayList EmployeeList;

		private Enum option;

		public void add() {

		}

		public void delete() {

		}

		public void update() {

		}

	}

}
